### PR TITLE
Ensure focusble targets are visible

### LINKED ISSUE #41: Tab trapping doesn't know elements are hidden by child <details>
Demonstrated here: https://html-is.glitch.me/throwaway/dialog.html

We'd try to focus on `details-dialog > details > input` and it silently fails. It'd be good if there's a way to know if `.focus()` failed and move on to the next element if so.

Relevant to http://github.com/whatwg/html/issues/4464.

### PR DESCRIPTION
**Pull request by muan**
Fixes #41, refer to considerations in https://github.com/github/details-dialog-element/issues/41#issuecomment-512864096.

This is a reliable visibility check (which comes with a perf cost as it triggers layout). I kept `.hidden` and `type=hidden` checks because they're relatively cheap and we use them often. When they were true we skip some `visible` calls.

Example use case:

```html
<details-dialog>
  <details>
    <details-menu><button><!-- focusable but not visible --></button></details-menu>
  </details>
</details-dialog>
```

and for autofocus:

```html
<details-dialog>
  <details>
    <details-menu><input autofocus><!-- focusable but not visible --></details-menu>
  </details>
  <button autofocus></button>
</details-dialog>
```

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -32,7 +32,11 @@ function keydown(event: KeyboardEvent): void {
 }
 
 function focusable(el: Focusable): boolean {
-  return el.tabIndex >= 0 && !el.disabled && !el.hidden && (!el.type || el.type !== 'hidden') && !el.closest('[hidden]')
+  return el.tabIndex >= 0 && !el.disabled && !el.hidden && (!el.type || el.type !== 'hidden') && visible(el)
+}
+
+function visible(el): boolean {
+  return el.offsetWidth > 0 || el.offsetHeight > 0
```
Comment (keithamus) [inline index.js]: Minor nit, but should `visible(el)` also contain the `!el.hidden` and `(!el.type || el.type !== 'hidden')` logic?
